/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ParameterImport } from './routes/parameter'

// Create Virtual Routes

const LinkTestLazyImport = createFileRoute('/link-test')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LinkTestLazyRoute = LinkTestLazyImport.update({
  path: '/link-test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/link-test.lazy').then((d) => d.Route))

const ParameterRoute = ParameterImport.update({
  path: '/parameter',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/parameter': {
      id: '/parameter'
      path: '/parameter'
      fullPath: '/parameter'
      preLoaderRoute: typeof ParameterImport
      parentRoute: typeof rootRoute
    }
    '/link-test': {
      id: '/link-test'
      path: '/link-test'
      fullPath: '/link-test'
      preLoaderRoute: typeof LinkTestLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ParameterRoute,
  LinkTestLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/parameter",
        "/link-test"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/parameter": {
      "filePath": "parameter.tsx"
    },
    "/link-test": {
      "filePath": "link-test.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
